export const NAV_ROUTES = {
  home: "/",
  products: "/products",
  categories: "/categories",
  offers: "/offers",
  contact: "/contact",
  about: "/about",
  favorites: "/wishlist",
  cart: "/cart",
  looks: "/looks",
  magazine: "/magazine",
  newArrivals: "/new-arrivals",
  bestSellers: "/best-sellers",
  packages: "/packages",
  terms: "/terms",
  privacy: "/privacy-policy",
  shipping: "/shipping-policy",
  returns: "/return-policy",
  discover: "/makeup-guide",
  account: "/account",
  search: "/search",
  legalPolicies: "/legal-policies",
  faq: "/faq",
  trackOrder: "/track-order",
};